# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 07:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 8, 42, 28, 432836), verbose_name='发送时间'),
        ),
    ]
