# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180507_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 7, 16, 6, 37, 913091), verbose_name='发送时间'),
        ),
    ]
